---
- name: Add Percona yum repository
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Install deltarpm
  yum:
    name: deltarpm
    state: latest

- name: update centos 7
  yum:  name=* update_cache=yes state=latest

- name: Install Percona Server 5.7
  yum:
    name: Percona-Server-server-57
    state: present
  notify: start mysql

- name: Change root password
  shell: |
    temp_password=$(grep password /var/log/mysqld.log | awk '{print $NF}' | head -n1)
    mysql_passwd="Quang12345@#$"
    echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '$mysql_passwd'; flush privileges;" > reset_pass.sql
    mysql -u root --password=$temp_password --connect-expired-password < reset_pass.sql